POSTGRES_DB: servicetracker
POSTGRES_USER: "{{ vault_POSTGRES_USER }}"
POSTGRES_PASSWORD: "{{ vault_POSTGRES_PASSWORD }}"
RABBITMQ_USER: "{{ vault_RABBITMQ_USER }}"
RABBITMQ_PASSWORD: "{{ vault_RABBITMQ_PASSWORD }}"
PGADMIN_EMAIL: "{{ vault_PGADMIN_EMAIL }}"
PGADMIN_PASSWORD: "{{ vault_PGADMIN_PASSWORD }}"




