services:
  servicetracker.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5092:8080"
  rabbitmq:
    healthcheck:
      start_period: 60s
